# Generated by Django 4.1.7 on 2023-12-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloguser',
            old_name='number',
            new_name='mobileno',
        ),
    ]
