# Generated by Django 4.1.7 on 2023-12-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_rename_number_bloguser_mobileno'),
    ]

    operations = [
        migrations.CreateModel(
            name='newpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('bimg', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
    ]
