# Generated by Django 4.1.7 on 2023-12-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_newpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='recipe',
            field=models.TextField(null=True),
        ),
    ]
